### ISSUE TITLE
Sri Query of referenced items

### ISSUE THREAD

**Issue by stefanvds1** [katholiek-onderwijs-vlaanderen/sri4node#120]
I have Events and i have Attendees.

The attendees go to an event, so in the DB there is a key to the event, in the resource there is a reference:

```
 map: {
    key: {},
    person: {},
    participationStatus: {},
    role: {},
    event: {references: '/events'},
    attended: {}
  },
```

when i filter on this via /events/attendees?event.href=**/events/{guid}** it gives 0 results
when i filter on this via /events/attendees?event.href=**{guid}** the filter works.

https://vsko-events-api-test.herokuapp.com/events/attendees?event.href=f557413a-dc9a-452c-8d62-2393b418c879

**Comment by stefanvds1** [comment]
The issue has become bigger now. It means i also can't select attendees of multiple events. 
/events/attendees?event.href={guid},{secondguid} gives 0 results.
also event.href and event.href**s** is the same?

**Comment by jgovaerts** [comment]
You need to define a filterReferencedType in the query object:
```
query: {
                    foo: $q.filterReferencedType('/events','event'),
                    defaultFilter: $q.defaultFilter
                },
```
Otherwise you search with the defaultFilter. With filterReferencedType you can search like /events/attendees?event=/events/{guid1},/events/{guid2}.

See [relevant sri4node documentation](https://github.com/katholiek-onderwijs-vlaanderen/sri4node#filterreferencedtypetype-columnname).

But I think it is not obvious that you have to configure sri4node like this for referencing. I will look into a way to use filterReferencedType by default if a reference is specified in the map.
