### ISSUE TITLE
Generalize exception handling on plugin-in functions

### ISSUE THREAD

**Issue by dimitrydhondt** [katholiek-onderwijs-vlaanderen/sri4node#13]
When rejecting a promise, any of the functions should be able to indicate the required status code. Right now, it is hard coded in the pipeline.

For example an afterupdate function will always generate 500 Internal Error when rejecting.

If I need want to return 403 Forbidden for some reason, after I have inserted (on my local transaction), than I cannot specify the desired status 403. This should be under control of the sri4node consumer.

**Comment by dimitrydhondt** [comment]
We should do this quickly, as it will be very much harder as more projects depend on it... Should be first priority.

**Comment by dimitrydhondt** [comment]
If we allow the plugin-function to set a statusCode on the error object, then we can do this in an gradual way. If the statusCode is not set, the defaults, depending on what kind of function (validation, query, secure, etc..) would kick in, but a user could still be able to override the default

**Comment by dimitrydhondt** [comment]
This would leave all contracts in sri4node to remain stable.

**Comment by dimitrydhondt** [comment]
After talking with Johannes on this we agreed to implement a (backwards compatible) way to reject a promise on an afterread/afterinsert/afterupdate and afterdelete method, that allows for more control over the response to the client. 

Johannes, when this is implemented please close this issue, ok ?

Thanks !

Dimi

**Comment by rodrigouroz** [comment]
Has there been any advance on this?
I need it for the module sri4node-security-api.

Can you explain to me what you have thought so I can do this myself?

Perhaps we can create a basic hierarchy or objects than inherit Error, and then we use the prototype of the object to determine the status to send to the client?

**Comment by rodrigouroz** [comment]
I mean, any after* function can then do:
```
throw new UnauthorizedError('some message')
```
and then when responding to the client we check:
```
if (err instanceOf UnauthorizedError) { ...
```
or more easily, the error object contains the status code and the body to return. What do you think?

**Comment by dimitrydhondt** [comment]
@jgovaerts Can you update Rodri ? and perhaps share the doc on how we would implement it ?

**Comment by dimitrydhondt** [comment]
Don't forget to document in README.md

**Comment by dimitrydhondt** [comment]
I'm afraid something went wrong with the communication on this. We need to go over the technical design.

**Comment by dimitrydhondt** [comment]
We nned to discuss this document :+1: 
https://docs.google.com/document/d/1e7MRRf9P_f8eqmw4N-sPuzLp74TwbPZICgwtKYwEst0/edit?usp=sharing

**Comment by dimitrydhondt** [comment]
Hej @rodrigouroz,

The way I understand your implementation is that the after* functions can receive a batch of elements at once. There are 2 possible reasons : 

- A GET on a list resource
- A /batch operation

A /batch operation itself may contain a GET on a list resource, so a mixed situation can occur.

Now the SRI reply for a batch needs to be different from a non-batch. I.e.: a batch needs to return an array with responses to the operations in the original batch. The status code on the batch needs to be MAX(all status codes for operations in the batch).

So I think the interface for the after* operations should return individual responses. I think we can keep the current mechanism, as it uses standard express names for the fields (which makes lie easier on our brains :-)).

My 2 questions are : 

1) When receiving the array of elements in an after* function, we currently get { path: '...', body: {} }.
Do we need this 'path' ? Is it not already a part of the resource via $$meta.permalink ?

2) When multiple responses are returned by the after* functions, are they combined into a valid response for batch operations ?

Dimi

**Comment by rodrigouroz** [comment]
@dimitrydhondt 

You're absolutely right. When I refactored the after* functions I had only in mind the current scenarios because we needed to quickly implement the new security module, so it only reflects the current possible Batch operations. I guess that when there's a full refactor of the batch operations to support all verbs we'll have to check this out.

My answers:

1) When you PUT a resource it doesn't have a $$meta section, therefore the after* function needs to receive the path (it can't be req.route.path either because that's the path of the /batch route). That path comes from the "href" attribute of the batch request section. Makes sense?

2) No, the first request that fails makes the whole batch fail. First all the batch requests are checked against the secure functions, if any fails, the batch fails. If all pass, then all the batch request are processed. This avoids the situation of having some batch requests processed and others not. Of course this needs a refactor as well when the batch mechanism is changed.

I think the earliest we do this the better: full batch implementation according to the specs plus refactor of all the existing middlewares (cache, secure, etc) to go along with this.

**Comment by dimitrydhondt** [comment]
Yes, Luckily we already have a lot of tests...

**Comment by dimitrydhondt** [comment]
We need to think this through very well. It all fits together. I was also reading your doc on the secure cache, and I think it also touches upon this. We'll need to bump the major version when we do this.

**Comment by jgovaerts** [comment]
In the 2.0 refactor all handler functions can throw SriError object to generate an error with a custom status code  . At top level errors are catched. In case of an SriError the SriError object determines the status code, other errors always generate 500 errors.
