### ISSUE TITLE
customRoute streamingHandler should not need to wait until the writing to the stream has ended to return

### ISSUE THREAD

**Issue by mrft** [katholiek-onderwijs-vlaanderen/sri4node#159]
in customRoutes
streamingHandler: async (tx, sriReq, stream) => {

}
now is expected to only resolve the promise when everything is written to the stream. i think it would be nicer if that is not necessary.
So instead of awaiting, can't we just monitor the express output stream to know when it's done?

**Comment by jgovaerts** [comment]
The interface of the streamingHandler remains so that the function only resolves when done with writing in the stream. Then sri4node will properly close the stream by writing 'null'. This seems to be the most easy and error prone way. Otherwise some other mechanism would be needed like make it obligated for streamingHandler to write 'null' at the end or send an event when done (both could be forgotten) .

The related busBoy ticket is fixed in another way.
